apiVersion: v1
kind: Service
metadata:
  name: beam2
  labels:
    app: beam2
spec:
  ports:
    - name: http
      port: 80
    - name: mysql
      port: 3306
  selector:
    app: beam2
  type: NodePort
